script:
- docker login --username devopscorndel --password $dockerhubpass
- docker build --target production --tag devopscorndel/travisimage:latest .
- docker push devopscorndel/travisimage:latest
- docker login --username=rusab36@gmail.com --password=$(heroku auth:herokutoken) registry.heroku.com
- docker pull devopscorndel/travisimage:latest
- docker tag devopscorndel/travisimage:latest registry.heroku.com/devops-workshhop7/web
- docker push registry.heroku.com/devops-workshhop7/web
- heroku container:release web -a travisimage:latest
env,global:
  secure: S0UEhFQPcO5DoBJGd7u+kz2Ne+OFnB/HBtwPKOr6R4eiINykBeqluP1GdfRHHQy6NahzTWXd/5rpn9qXVddaUwZu3+22tjbBCFcKMLQ9qjS4PM6ntMwYVLj3GFnfY1sgjRh7hoylzADU+8SFlXEo4Fvjbw0SRCNvfPcEYmA49HSciirymObLW7W3niC7Cukg1RiN34zgjhhgQnttP/BVF7wOCMn7t0wSJEQsuxkEltk7dtoC8grzY76pCtDsvqp9EFJfXBjomMPHTdp7Fi+mWvNdmhmJeVRSwo64GUb/m3n8A7ukr8hlHg5Yw9PjwAWcMdwm/lT4MmfJdnkV1MCQCzXmNg2U4wWZBnwoCpaifhqa6H52ySAJEEXaYSeKp4l4xKbBuqGl+5q5AxmmhIGytKNHVZeKX+HrlNjNB856fMgtUhRDsrs8AQ4OvgwoMisy/BKx6QqMmiunJ8U1snMxv1ebKiHIPz7qGZ4ssbZsKYMFsTCRmqYLAqU9ZJfaZPAfHFOTTmkwf27cT4TVQhy6x7ujjoOwVjBuYdTe7YFLPaIMs3ymyp/F+vSf9S9tnh1PlHLzCm3wXr6tYzscS4h+/IrP6L2os/KK9btKBkLlQF1LQi7lUCdWvMgXnWCKSZe5O+ltDFXtqQIYwOJrgADbj6hXbP8Ab5NGgxjWRN2RVUI=
